// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using SIGSTO.Data;

#nullable disable

namespace SIGSTO.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.19");

            modelBuilder.Entity("SIGSTO.Models.AccordDeStage", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("CandidatureId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("CheminFichier")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("DateAttache")
                        .HasColumnType("TEXT");

                    b.Property<string>("Periode")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<string>("Theme")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("CandidatureId")
                        .IsUnique();

                    b.ToTable("AccordsDeStage");
                });

            modelBuilder.Entity("SIGSTO.Models.Attestation", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("CandidatureId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("CheminFichier")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("DateGen")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("CandidatureId")
                        .IsUnique();

                    b.ToTable("Attestations");
                });

            modelBuilder.Entity("SIGSTO.Models.Candidature", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("CheminCV")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<string>("CheminLM")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<string>("CheminLR")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<string>("CheminReleves")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("DateSoumission")
                        .HasColumnType("TEXT");

                    b.Property<int?>("EncadrantId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("EtudiantId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("OffreId")
                        .HasColumnType("INTEGER");

                    b.Property<float>("Score")
                        .HasColumnType("REAL");

                    b.Property<int>("StatutCandidature")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("EncadrantId");

                    b.HasIndex("EtudiantId");

                    b.HasIndex("OffreId");

                    b.ToTable("Candidatures");
                });

            modelBuilder.Entity("SIGSTO.Models.Convention", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("CandidatureId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("CheminAssurance")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<string>("CheminConv")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<int>("Statut")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("CandidatureId")
                        .IsUnique();

                    b.ToTable("Conventions");
                });

            modelBuilder.Entity("SIGSTO.Models.Evaluation", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Appreciation")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("CandidatureId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("DateEvaluation")
                        .HasColumnType("TEXT");

                    b.Property<int>("EncadrantId")
                        .HasColumnType("INTEGER");

                    b.Property<float>("Note")
                        .HasColumnType("REAL");

                    b.HasKey("Id");

                    b.HasIndex("CandidatureId")
                        .IsUnique();

                    b.HasIndex("EncadrantId");

                    b.ToTable("Evaluations");
                });

            modelBuilder.Entity("SIGSTO.Models.Message", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("CheminFichier")
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<string>("Contenu")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("DateEnvoi")
                        .HasColumnType("TEXT");

                    b.Property<int>("EncadrantId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("EtudiantId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Expediteur")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("EncadrantId");

                    b.HasIndex("EtudiantId");

                    b.ToTable("Messages");
                });

            modelBuilder.Entity("SIGSTO.Models.OTP", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("Expiration")
                        .HasColumnType("TEXT");

                    b.Property<string>("OTPCode")
                        .IsRequired()
                        .HasMaxLength(6)
                        .HasColumnType("TEXT");

                    b.Property<int>("UserId")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("Utilise")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("UserId")
                        .IsUnique();

                    b.ToTable("OTPs");
                });

            modelBuilder.Entity("SIGSTO.Models.Offre", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("DateDebut")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("DateFin")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("DateLimitePostule")
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Filiere")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<int>("GestionnaireId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("MotsCles")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("NbrPlaces")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Statut")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Titre")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("TEXT");

                    b.Property<int>("Type")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("GestionnaireId");

                    b.ToTable("Offres");
                });

            modelBuilder.Entity("SIGSTO.Models.Utilisateur", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Discriminator")
                        .IsRequired()
                        .HasMaxLength(13)
                        .HasColumnType("TEXT");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<bool>("EmailVerifie")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Nom")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Prenom")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<int>("Role")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.ToTable("Utilisateurs");

                    b.HasDiscriminator().HasValue("Utilisateur");

                    b.UseTphMappingStrategy();
                });

            modelBuilder.Entity("SIGSTO.Models.Encadrant", b =>
                {
                    b.HasBaseType("SIGSTO.Models.Utilisateur");

                    b.Property<string>("Departement")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.HasDiscriminator().HasValue("Encadrant");
                });

            modelBuilder.Entity("SIGSTO.Models.Etudiant", b =>
                {
                    b.HasBaseType("SIGSTO.Models.Utilisateur");

                    b.Property<DateTime?>("DateNaissance")
                        .HasColumnType("TEXT");

                    b.Property<string>("Etablissement")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<string>("Filiere")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<bool>("Handicap")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Sexe")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("TEXT");

                    b.HasDiscriminator().HasValue("Etudiant");
                });

            modelBuilder.Entity("SIGSTO.Models.GestionnaireDesStages", b =>
                {
                    b.HasBaseType("SIGSTO.Models.Utilisateur");

                    b.HasDiscriminator().HasValue("Gestionnaire");
                });

            modelBuilder.Entity("SIGSTO.Models.AccordDeStage", b =>
                {
                    b.HasOne("SIGSTO.Models.Candidature", "Candidature")
                        .WithOne("AccordDeStage")
                        .HasForeignKey("SIGSTO.Models.AccordDeStage", "CandidatureId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Candidature");
                });

            modelBuilder.Entity("SIGSTO.Models.Attestation", b =>
                {
                    b.HasOne("SIGSTO.Models.Candidature", "Candidature")
                        .WithOne("Attestation")
                        .HasForeignKey("SIGSTO.Models.Attestation", "CandidatureId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Candidature");
                });

            modelBuilder.Entity("SIGSTO.Models.Candidature", b =>
                {
                    b.HasOne("SIGSTO.Models.Encadrant", "Encadrant")
                        .WithMany()
                        .HasForeignKey("EncadrantId")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.HasOne("SIGSTO.Models.Etudiant", "Etudiant")
                        .WithMany()
                        .HasForeignKey("EtudiantId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("SIGSTO.Models.Offre", "Offre")
                        .WithMany("Candidatures")
                        .HasForeignKey("OffreId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("Encadrant");

                    b.Navigation("Etudiant");

                    b.Navigation("Offre");
                });

            modelBuilder.Entity("SIGSTO.Models.Convention", b =>
                {
                    b.HasOne("SIGSTO.Models.Candidature", "Candidature")
                        .WithOne("Convention")
                        .HasForeignKey("SIGSTO.Models.Convention", "CandidatureId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Candidature");
                });

            modelBuilder.Entity("SIGSTO.Models.Evaluation", b =>
                {
                    b.HasOne("SIGSTO.Models.Candidature", "Candidature")
                        .WithOne("Evaluation")
                        .HasForeignKey("SIGSTO.Models.Evaluation", "CandidatureId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SIGSTO.Models.Encadrant", "Encadrant")
                        .WithMany()
                        .HasForeignKey("EncadrantId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("Candidature");

                    b.Navigation("Encadrant");
                });

            modelBuilder.Entity("SIGSTO.Models.Message", b =>
                {
                    b.HasOne("SIGSTO.Models.Encadrant", "Encadrant")
                        .WithMany()
                        .HasForeignKey("EncadrantId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("SIGSTO.Models.Etudiant", "Etudiant")
                        .WithMany()
                        .HasForeignKey("EtudiantId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("Encadrant");

                    b.Navigation("Etudiant");
                });

            modelBuilder.Entity("SIGSTO.Models.OTP", b =>
                {
                    b.HasOne("SIGSTO.Models.Etudiant", "Etudiant")
                        .WithOne("OTP")
                        .HasForeignKey("SIGSTO.Models.OTP", "UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Etudiant");
                });

            modelBuilder.Entity("SIGSTO.Models.Offre", b =>
                {
                    b.HasOne("SIGSTO.Models.GestionnaireDesStages", "Gestionnaire")
                        .WithMany()
                        .HasForeignKey("GestionnaireId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Gestionnaire");
                });

            modelBuilder.Entity("SIGSTO.Models.Candidature", b =>
                {
                    b.Navigation("AccordDeStage");

                    b.Navigation("Attestation");

                    b.Navigation("Convention");

                    b.Navigation("Evaluation");
                });

            modelBuilder.Entity("SIGSTO.Models.Offre", b =>
                {
                    b.Navigation("Candidatures");
                });

            modelBuilder.Entity("SIGSTO.Models.Etudiant", b =>
                {
                    b.Navigation("OTP");
                });
#pragma warning restore 612, 618
        }
    }
}
